# Generated by Django 5.0.6 on 2024-09-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='destination',
            new_name='destination_city',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='photo',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passport_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='visa_document',
            field=models.ImageField(upload_to=''),
        ),
    ]
