# Generated by Django 6.0.5 on 2026-06-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('po_box_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='P.O.BOX Number')),
                ('emergency_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('visa_document', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_city', models.CharField(max_length=50)),
                ('destination_city', models.CharField(max_length=50)),
            ],
        ),
    ]
